# Generated by Django 3.2.12 on 2022-03-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vehiclemodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleBrand',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
    ]
