# Generated by Django 3.2.12 on 2022-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_auto_20220316_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Passat', 'Passat'), ('E Class', 'E Class'), ('S Class', 'S Class'), ('C Class', 'C Class'), ('G Class', 'G Class'), ('E 90', 'E 90'), ('E 60', 'E 60'), ('F 10', 'F 10'), ('Mustang', 'Mustang')], max_length=7)),
            ],
        ),
    ]
