# Generated by Django 3.2.12 on 2022-03-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
    ]
