# Generated by Django 3.2.12 on 2022-03-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_vehicle_manufacture_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
