# Generated by Django 3.2.12 on 2022-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_type',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('Electric', 'Electric'), ('Gas', 'Gas')], max_length=8),
        ),
    ]
