# Generated by Django 3.2.12 on 2022-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220318_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='euro_standard',
            field=models.CharField(choices=[('Euro 1', 'Euro 1'), ('Euro 2', 'Euro 2'), ('Euro 3', 'Euro 3'), ('Euro 4', 'Euro 4'), ('Euro 5', 'Euro 5'), ('Euro 6', 'Euro 6')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
