# Generated by Django 3.2.12 on 2022-03-18 14:21

from django.db import migrations, models
import registration.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_vehicle_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default=1, max_length=20, validators=[registration.common.validators.validate_only_letters]),
            preserve_default=False,
        ),
    ]
