# Generated by Django 3.2.12 on 2022-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_publishedadvert_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedadvert',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
