# Generated by Django 3.2.12 on 2022-03-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
