# Generated by Django 3.2.12 on 2022-03-28 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Very satisfied', 'Very satisfied'), ('Satisfied', 'Satisfied'), ('Neither agree nor disagree', 'Neither agree nor disagree'), ('Dissatisfied', 'Dissatisfied'), ('Very dissatisfied', 'Very dissatisfied')], max_length=26)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
