# Generated by Django 3.2.12 on 2022-03-29 13:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0034_auto_20220329_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='CarModel',
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ('name',)},
        ),
    ]
