# Generated by Django 3.2.12 on 2022-03-29 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20220329_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
