# Generated by Django 3.2.12 on 2022-03-29 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_make_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='additional_info',
            field=models.CharField(default=1, max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
