# Generated by Django 3.2.12 on 2022-03-29 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_vehicle_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='additional_info',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
